
before_script:
    - apt update && apt install python-pip libssl-dev git -y
    - pip install ansible

test_server:
    image: ubuntu:16.04
    script:
        - ansible-galaxy install -p tests/ -r tests/requirements.yml
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files" --syntax-check
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files" --connection=local
        - >
          ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files" --connection=local
          | grep -q 'changed=0.*failed=0'
          && (echo 'Idempotence test: pass' && exit 0)
          || (echo 'Idempotence test: fail' && exit 1)

test_client:
    image: ubuntu:16.04
    script:
        - ansible-galaxy install -p tests/ -r tests/requirements.yml
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-clients deploy_key_dir={{ playbook_dir }}/files" --syntax-check
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-clients deploy_key_dir={{ playbook_dir }}/files" --connection=local
        - >
          ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-clients deploy_key_dir={{ playbook_dir }}/files" --connection=local
          | grep -q 'changed=0.*failed=0'
          && (echo 'Idempotence test: pass' && exit 0)
          || (echo 'Idempotence test: fail' && exit 1)

test_server_no_tls:
    image: ubuntu:16.04
    script:
        - ansible-galaxy install -p tests/ -r tests/requirements.yml
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files openvpn_tls_push=False" --syntax-check
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files openvpn_tls_push=False" --connection=local
        - >
          ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files openvpn_tls_push=False" --connection=local
          | grep -q 'changed=0.*failed=0'
          && (echo 'Idempotence test: pass' && exit 0)
          || (echo 'Idempotence test: fail' && exit 1)

test_client_no_tls:
    image: ubuntu:16.04
    script:
        - ansible-galaxy install -p tests/ -r tests/requirements.yml
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-clients deploy_key_dir={{ playbook_dir }}/files openvpn_tls_push=False" --syntax-check
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-clients deploy_key_dir={{ playbook_dir }}/files openvpn_tls_push=False" --connection=local
        - >
          ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-clients deploy_key_dir={{ playbook_dir }}/files openvpn_tls_push=False" --connection=local
          | grep -q 'changed=0.*failed=0'
          && (echo 'Idempotence test: pass' && exit 0)
          || (echo 'Idempotence test: fail' && exit 1)

test_server_ccd_yes:
    image: ubuntu:16.04
    script:
        - ansible-galaxy install -p tests/ -r tests/requirements.yml
        - touch tests/openvpn/templates/localhost.j2
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files openvpn_ccd=True" --syntax-check
        - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files openvpn_ccd=True" --connection=local
        - >
          ansible-playbook tests/test.yml -i tests/inventory --extra-vars "remote_host=lab-servers deploy_key_dir={{ playbook_dir }}/files openvpn_ccd=True" --connection=local
          | grep -q 'changed=0.*failed=0'
          && (echo 'Idempotence test: pass' && exit 0)
          || (echo 'Idempotence test: fail' && exit 1)

