---
- name: OpenVPN - Install openvpn
  apt: 
      name: "{{ item }}"
      state: present 
      update_cache: yes
  with_items: [openvpn, openssl]
  when: ansible_distribution == 'Ubuntu'

- name: OpenVPN - Create keys directory
  file:
      path: "{{ openvpn_dir }}/keys" 
      mode: 0700
      owner: root
      group: root
      state: directory

- name: OpenVPN - Transfer server template
  template:
      src: server.conf.j2
      dest: /etc/openvpn/server.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
  notify: restart openvpn
  when: inventory_hostname in groups['lab-servers']

- name: OpenVPN - Transfer client template
  template:
      src: client.conf.j2
      dest: /etc/openvpn/client.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
  notify: restart openvpn
  when: inventory_hostname in groups['lab-clients']

- name: OpenVPN - Transfer key
  copy:
      src: "{{ local_openvpn_keydir }}/{{ item }}.key"
      dest: "{{ openvpn_keydir }}" 
      owner: root
      group: root
      mode: 0600
  with_items:
      - "{{ inventory_hostname }}"
  notify: reload openvpn

- name: OpenVPN - TLS key
  copy:
      src: "{{ local_openvpn_keydir }}/{{ item }}.key"
      dest: "{{ openvpn_keydir }}" 
      owner: root
      group: root
      mode: 0600
  with_items:
      - ta
  notify: reload openvpn
  when: openvpn_tls_push == True

- name: OpenVPN - Transfer server only files
  copy:
      src: "{{ local_openvpn_keydir }}/{{ item }}"
      dest: "{{ openvpn_keydir }}" 
      owner: root
      group: root
      mode: 0644
  with_items:
      - crl.pem
      - "{{ openvpn_server_dh }}.pem"
  notify: reload openvpn
  when: inventory_hostname in groups['lab-servers']

- name: OpenVPN - Transfer certificates
  copy:
      src: "{{ local_openvpn_keydir }}/{{ item }}"
      dest: "{{ openvpn_keydir }}" 
      owner: root
      group: root
      mode: 0644
  with_items:
      - ca.crt
      - "{{ inventory_hostname }}.crt"
  notify: reload openvpn

- block:
    - name: OpenVPN - CCD - Create CCD
      file:  
          path: "{{ openvpn_ccd_dir }}" 
          mode: 0700
          owner: root
          group: root
          state: directory
      notify: reload openvpn
    
    - name: OpenVPN - CCD - Copy client templates
      template:
          src: "{{ item }}.j2"
          dest: "{{ openvpn_ccd_dir }}/{{ item }}"
          owner: root
          group: root
          mode: 0600
          backup: yes
      with_items: 
          - "{{ groups['lab-clients'] }}"
      notify: reload openvpn
      register: rst
      ignore_errors: yes

  when: (openvpn_ccd == True) and (inventory_hostname in groups['lab-servers']) 
